In [3]:
import numpy as np
import pandas as pd
pd.set_option('display.max_rows',100)

In [4]:
df = pd.read_csv('Bikes.csv')

In [5]:
print(df)

                                  bike_name     price       city  kms_driven  \
0        TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1               Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                      Triumph Daytona 675R  600000.0      Delhi       110.0   
3                      TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
...                                     ...       ...        ...         ...   
32643                Hero Passion Pro 100cc   39000.0      Delhi     22000.0   
32644                  TVS Apache RTR 180cc   30000.0     Karnal      6639.0   
32645              Bajaj Avenger Street 220   60000.0      Delhi     20373.0   
32646             Hero Super Splendor 125cc   15600.0     Jaipur     84186.0   
32647                    Bajaj Pulsar 150cc   22000.0       Pune     60857.0   

             owner   age  power        

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   bike_name   32648 non-null  object 
 1   price       32648 non-null  float64
 2   city        32648 non-null  object 
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  object 
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  object 
dtypes: float64(4), object(4)
memory usage: 2.0+ MB


In [7]:
df.head()

bike_name     price       city  kms_driven  \
0    TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1           Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                  Triumph Daytona 675R  600000.0      Delhi       110.0   
3                  TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4  Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   

         owner  age  power          brand  
0  First Owner  3.0  110.0            TVS  
1  First Owner  4.0  350.0  Royal Enfield  
2  First Owner  8.0  675.0        Triumph  
3  First Owner  4.0  180.0            TVS  
4  First Owner  3.0  150.0         Yamaha

In [8]:
df.describe()

price     kms_driven           age         power
count  3.264800e+04   32648.000000  32648.000000  32648.000000
mean   6.829542e+04   26344.625184      8.048211    213.511302
std    9.071860e+04   22208.527695      4.031700    134.428868
min    4.400000e+03       1.000000      1.000000    100.000000
25%    2.500000e+04   12000.000000      5.000000    150.000000
50%    4.300000e+04   20373.000000      7.000000    150.000000
75%    8.000000e+04   35000.000000     10.000000    220.000000
max    1.900000e+06  750000.000000     63.000000   1800.000000

In [9]:
#Catgorical data  
from sklearn.preprocessing import LabelEncoder  
le = LabelEncoder() 

df['bike_name'] = le.fit_transform(df['bike_name'])
df['bike_name'].value_counts()
df

bike_name     price       city  kms_driven        owner   age  power  \
0            401   35000.0  Ahmedabad     17654.0  First Owner   3.0  110.0   
1            295  119900.0      Delhi     11000.0  First Owner   4.0  350.0   
2            411  600000.0      Delhi       110.0  First Owner   8.0  675.0   
3            375   65000.0  Bangalore     16329.0  First Owner   4.0  180.0   
4            426   80000.0  Bangalore     10000.0  First Owner   3.0  150.0   
...          ...       ...        ...         ...          ...   ...    ...   
32643        151   39000.0      Delhi     22000.0  First Owner   4.0  100.0   
32644        375   30000.0     Karnal      6639.0  First Owner   9.0  180.0   
32645         15   60000.0      Delhi     20373.0  First Owner   6.0  220.0   
32646        176   15600.0     Jaipur     84186.0  First Owner  16.0  125.0   
32647         56   22000.0       Pune     60857.0  First Owner  13.0  150.0   

               brand  
0                TVS  
1      Royal Enfield  
2            Triumph  
3                TVS  
4             Yamaha  
...              ...  
32643           Hero  
32644            TVS  
32645          Bajaj  
32646           Hero  
32647          Bajaj  

[32648 rows x 8 columns]

In [10]:
df['city'] = le.fit_transform(df['city'])
df['owner'] = le.fit_transform(df['owner'])
df['brand'] = le.fit_transform(df['brand'])
df

bike_name     price  city  kms_driven  owner   age  power  brand
0            401   35000.0     6     17654.0      0   3.0  110.0     19
1            295  119900.0   118     11000.0      0   4.0  350.0     17
2            411  600000.0   118       110.0      0   8.0  675.0     20
3            375   65000.0    44     16329.0      0   4.0  180.0     19
4            426   80000.0    44     10000.0      0   3.0  150.0     21
...          ...       ...   ...         ...    ...   ...    ...    ...
32643        151   39000.0   118     22000.0      0   4.0  100.0      5
32644        375   30000.0   224      6639.0      0   9.0  180.0     19
32645         15   60000.0   118     20373.0      0   6.0  220.0      1
32646        176   15600.0   191     84186.0      0  16.0  125.0      5
32647         56   22000.0   330     60857.0      0  13.0  150.0      1

[32648 rows x 8 columns]

# 4 Splitting the Dataset into the Training set and Test set

In [11]:
x = df.drop("price", axis = 1)
y = df['price']
print(x.shape)
print(y.shape)

(32648, 7)
(32648,)


In [12]:
from sklearn.model_selection import train_test_split

train_test_split(x,y,test_size =0.2,random_state=0)


[       bike_name  city  kms_driven  owner   age  power  brand
 15296        151   118     22000.0      0   4.0  100.0      5
 15180          9   118     20245.0      2  11.0  220.0      1
 11583         72    14     41939.0      0   8.0  200.0      1
 20838         56   118     32588.0      0   9.0  150.0      1
 6083         151   258     12000.0      0   9.0  100.0      5
 ...          ...   ...         ...    ...   ...    ...    ...
 13123        257   282     13216.0      0   4.0  390.0     11
 19648          9    44     60000.0      0   9.0  220.0      1
 9845          15   118     20373.0      0   6.0  220.0      1
 10799        356   257     22697.0      0   7.0  125.0     18
 2732         354   244     14495.0      0   3.0  150.0     18
 
 [26118 rows x 7 columns],
        bike_name  city  kms_driven  owner   age  power  brand
 9763         194   330       140.0      0   3.0  160.0      6
 28214          9   118     20245.0      2  11.0  220.0      1
 24114        110   211   

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [14]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape) 

(26118, 7) (6530, 7) (26118,) (6530,)


In [15]:
x_train

bike_name  city  kms_driven  owner   age  power  brand
15296        151   118     22000.0      0   4.0  100.0      5
15180          9   118     20245.0      2  11.0  220.0      1
11583         72    14     41939.0      0   8.0  200.0      1
20838         56   118     32588.0      0   9.0  150.0      1
6083         151   258     12000.0      0   9.0  100.0      5
...          ...   ...         ...    ...   ...    ...    ...
13123        257   282     13216.0      0   4.0  390.0     11
19648          9    44     60000.0      0   9.0  220.0      1
9845          15   118     20373.0      0   6.0  220.0      1
10799        356   257     22697.0      0   7.0  125.0     18
2732         354   244     14495.0      0   3.0  150.0     18

[26118 rows x 7 columns]

In [16]:
y_train

15296     39000.0
15180     41000.0
11583     48000.0
20838     25000.0
6083      27500.0
           ...   
13123    196700.0
19648     35000.0
9845      60000.0
10799     32000.0
2732      98000.0
Name: price, Length: 26118, dtype: float64

In [17]:
x_test

bike_name  city  kms_driven  owner   age  power  brand
9763         194   330       140.0      0   3.0  160.0      6
28214          9   118     20245.0      2  11.0  220.0      1
24114        110   211      3430.0      0   4.0  750.0      4
16697         15   282      8000.0      0   5.0  220.0      1
12930        288   118     20000.0      0   4.0  350.0     17
...          ...   ...         ...    ...   ...    ...    ...
1186          29   330     12000.0      0  10.0  100.0      1
28914        439   215     14500.0      0   4.0  250.0     21
19698        141   118     48587.0      0   8.0  150.0      5
21447        439   215     14500.0      0   4.0  250.0     21
2519         290   118     22550.0      0   6.0  350.0     17

[6530 rows x 7 columns]

In [18]:
y_test

9763      87000.0
28214     41000.0
24114    450000.0
16697     70000.0
12930    105000.0
           ...   
1186      26000.0
28914    123000.0
19698     25000.0
21447    123000.0
2519     109400.0
Name: price, Length: 6530, dtype: float64

In [19]:
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score


# 5 Feature Scaling 

In [20]:
#from sklearn.compose import ColumnTransformer

In [21]:
#transformer =  make_column_transformer((LabelEncoder(),[0]),remainder='passthrough')

In [22]:
scaler = StandardScaler()

In [23]:
x_train= scaler.fit_transform(x_train)  
x_test= scaler.transform(x_test)  


In [24]:
x_train

array([[-0.26232668, -0.57474291, -0.19600484, ..., -1.00576034,
        -0.84458001, -0.45063111],
       [-1.24002894, -0.57474291, -0.27414007, ...,  0.73148884,
         0.04707253, -0.96958361],
       [-0.80625962, -1.6564144 ,  0.69170928, ..., -0.01304652,
        -0.10153623, -0.96958361],
       ...,
       [-1.19871757, -0.57474291, -0.26844132, ..., -0.50940343,
         0.04707253, -0.96958361],
       [ 1.14914489,  0.87095264, -0.16497336, ..., -0.26122498,
        -0.65881906,  1.23596452],
       [ 1.13537443,  0.7357437 , -0.53013868, ..., -1.25393879,
        -0.47305812,  1.23596452]])

In [25]:
x_test

array([[ 0.03373809,  1.63020282, -1.16924476, ..., -1.25393879,
        -0.39875374, -0.32089298],
       [-1.24002894, -0.57474291, -0.27414007, ...,  0.73148884,
         0.04707253, -0.96958361],
       [-0.54462099,  0.39252102, -1.02276904, ..., -1.00576034,
         3.98520456, -0.58036923],
       ...,
       [-0.33117895, -0.57474291,  0.98768819, ..., -0.01304652,
        -0.47305812, -0.45063111],
       [ 1.72061874,  0.43412377, -0.52991607, ..., -1.00576034,
         0.26998566,  1.62517889],
       [ 0.69471989, -0.57474291, -0.17151802, ..., -0.50940343,
         1.01302944,  1.10622639]])

# 6 Applying Linear Regression

In [26]:
lr = LinearRegression(normalize =True)

In [27]:
pipe = make_pipeline(scaler,lr)

In [28]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression(normalize=True))])

# 8 testing model

In [29]:
pipe.predict(x_test)

array([ 95159.67205605,  30874.07246623, 421475.27178519, ...,
        35794.70077374, 110333.7386566 , 111488.33694994])

In [30]:
predict = pipe.predict(x_test)

In [31]:
r2_score(y_test,predict)

0.8523406197241166

# Applying Lasso and Ridge

In [32]:
ridge = Lasso()
pipe = make_pipeline(scaler,lr)
pipe.fit(x_train,y_train)
pipe.predict(x_test)
predict = pipe.predict(x_test)
r2_score(y_test,predict)

0.8523406197241166

In [33]:
ridge = Ridge()
pipe = make_pipeline(scaler,lr)
pipe.fit(x_train,y_train)
pipe.predict(x_test)
predict = pipe.predict(x_test)
r2_score(y_test,predict)

0.8523406197241166

In [34]:
import pickle

In [35]:
pickle.dump(pipe,open('model.pkl','wb'))